### PR TITLE
Kotlin conversion

### PR DESCRIPTION
**Pull request by dapp**
This is not part of the generate-kotlin effort.  Rather, it converts the code we use to generate java into kotlin.  This might make switching blueprint to generate kotlin code a little easier

### CODE REVIEW

**Comment by fkose696** [comment]
Kotlin related changes look good 👍 we'll need to cherry-pick the changes needed for #67 to this to keep them in sync

**Comment by dapp** [comment]
@fkose696  rebased this onto the work from https://github.com/Comcast/blueprint/pull/67

**Comment by dapp** [comment]
after we get this merged,  we can get back to converting the generated code to kotlin

**Comment by fkose696** [comment]
Can you revert the gradle related change?

**Comment by dapp** [comment]
> Can you revert the gradle related change?

done

**Review by fkose696 — APPROVED** [review]

**Pull request merged**
