### PR TITLE
Generalize loading indicators

### PR DESCRIPTION
**Pull request by dapp**
Change naming to be more general, and default to more generic loading indicator, rather than xfinity loading dots.

### CODE REVIEW

**Comment by dapp** [comment]
@fkose696  - can you please review?  After this change, we can release the official 2.0.0 version!

**Review by fkose696 — DISMISSED** [review]
Can you update the sample app to use the LoadingIndicator view type in the presenters?

**Comment by dapp** [comment]
@fkose696  -- done, I think?  Can you take a look, let me know if that's what you meant...

**Comment by fkose696** [comment]
Sorry I wasn't clear. I wasn't able to build the sample app due to the presenters in bluprint_sample package still using LoadingDotsView_VIEW_TYPE. Can you update them with the new view type?

**Comment by dapp** [comment]
> 

I think I fixed all of this in the latest commit.  Try pulling it again and let me know

**Review by fkose696 — DISMISSED** [review]
I just pushed it separately here https://github.com/Comcast/blueprint/pull/66

**Comment by dapp** [comment]
> I just pushed it separately here #66

Nice, Merged into this branch.

**Pull request merged**
